-- MySQL Script generated by MySQL Workbench
-- 11/08/17 01:01:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `horarios`.`trabajador` (
  `idtrabajador` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(35) NOT NULL,
  `celular` VARCHAR(13) NULL,
  `correo` VARCHAR(45) NULL,
  `fechaelim` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idtrabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo` ;

CREATE TABLE IF NOT EXISTS `horarios`.`grupo` (
  `idgrupo` INT NOT NULL,
  `nombre` VARCHAR(4) NOT NULL,
  `salon` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `horarios`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `rol` VARCHAR(1) NOT NULL,
  `trabajador_idtrabajador` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `trabajador_idtrabajador`),
  INDEX `fk_usuario_trabajador1_idx` (`trabajador_idtrabajador` ASC),
  CONSTRAINT `fk_usuario_trabajador1`
    FOREIGN KEY (`trabajador_idtrabajador`)
    REFERENCES `horarios`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`alumno` ;

CREATE TABLE IF NOT EXISTS `horarios`.`alumno` (
  `idalumno` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(35) NOT NULL,
  `idgrupo` INT NOT NULL,
  `fechaelim` TIMESTAMP(6) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_trabajador_idtrabajador` INT NOT NULL,
  PRIMARY KEY (`idalumno`, `idgrupo`, `usuario_idusuario`, `usuario_trabajador_idtrabajador`),
  INDEX `fk_alumno_grupo_idx` (`idgrupo` ASC),
  INDEX `fk_alumno_usuario1_idx` (`usuario_idusuario` ASC, `usuario_trabajador_idtrabajador` ASC),
  CONSTRAINT `fk_alumno_grupo`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `horarios`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_trabajador_idtrabajador`)
    REFERENCES `horarios`.`usuario` (`idusuario` , `trabajador_idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`periodo` ;

CREATE TABLE IF NOT EXISTS `horarios`.`periodo` (
  `idperiodo` INT NOT NULL,
  `tipo` VARCHAR(1) NOT NULL,
  `año` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`hora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`hora` ;

CREATE TABLE IF NOT EXISTS `horarios`.`hora` (
  `idhora` INT NOT NULL,
  `Inicio` VARCHAR(5) NOT NULL,
  `Final` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idhora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`dia` ;

CREATE TABLE IF NOT EXISTS `horarios`.`dia` (
  `iddia` INT NOT NULL,
  `dia` INT NOT NULL,
  PRIMARY KEY (`iddia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`clase` ;

CREATE TABLE IF NOT EXISTS `horarios`.`clase` (
  `idclase` INT NOT NULL,
  `idalumno` INT NOT NULL,
  `idgrupo` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `periodo_idperiodo` INT NOT NULL,
  `hora_idhora` INT NOT NULL,
  `dia_iddia` INT NOT NULL,
  PRIMARY KEY (`idclase`, `periodo_idperiodo`, `hora_idhora`, `dia_iddia`),
  INDEX `fk_alumno_has_trabajador_trabajador1_idx` (`idtrabajador` ASC),
  INDEX `fk_alumno_has_trabajador_alumno1_idx` (`idalumno` ASC, `idgrupo` ASC),
  INDEX `fk_clase_periodo1_idx` (`periodo_idperiodo` ASC),
  INDEX `fk_clase_hora1_idx` (`hora_idhora` ASC),
  INDEX `fk_clase_dia1_idx` (`dia_iddia` ASC),
  CONSTRAINT `fk_alumno_has_trabajador_alumno1`
    FOREIGN KEY (`idalumno` , `idgrupo`)
    REFERENCES `horarios`.`alumno` (`idalumno` , `idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_trabajador_trabajador1`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `horarios`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `horarios`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_hora1`
    FOREIGN KEY (`hora_idhora`)
    REFERENCES `horarios`.`hora` (`idhora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_dia1`
    FOREIGN KEY (`dia_iddia`)
    REFERENCES `horarios`.`dia` (`iddia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`asisAlumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`asisAlumno` ;

CREATE TABLE IF NOT EXISTS `horarios`.`asisAlumno` (
  `idasisAlumno` INT NOT NULL,
  `idclase` INT NOT NULL,
  `idperiodo` INT NOT NULL,
  `idhora` INT NOT NULL,
  `iddia` INT NOT NULL,
  `registro` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idasisAlumno`, `idclase`, `idperiodo`, `idhora`, `iddia`),
  INDEX `fk_asisAlumno_clase1_idx` (`idclase` ASC, `idperiodo` ASC, `idhora` ASC, `iddia` ASC),
  CONSTRAINT `fk_asisAlumno_clase1`
    FOREIGN KEY (`idclase` , `idperiodo` , `idhora` , `iddia`)
    REFERENCES `horarios`.`clase` (`idclase` , `periodo_idperiodo` , `hora_idhora` , `dia_iddia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`asisTrabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`asisTrabajador` ;

CREATE TABLE IF NOT EXISTS `horarios`.`asisTrabajador` (
  `idasisTrabajador` INT NOT NULL,
  `idclase` INT NOT NULL,
  `idperiodo` INT NOT NULL,
  `idhora` INT NOT NULL,
  `iddia` INT NOT NULL,
  `registro` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idasisTrabajador`, `idclase`, `idperiodo`, `idhora`, `iddia`),
  INDEX `fk_asisTrabajador_clase1_idx` (`idclase` ASC, `idperiodo` ASC, `idhora` ASC, `iddia` ASC),
  CONSTRAINT `fk_asisTrabajador_clase1`
    FOREIGN KEY (`idclase` , `idperiodo` , `idhora` , `iddia`)
    REFERENCES `horarios`.`clase` (`idclase` , `periodo_idperiodo` , `hora_idhora` , `dia_iddia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
