-- MySQL Script generated by MySQL Workbench
-- 11/17/17 01:29:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `horarios`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`usuario` ;

CREATE TABLE IF NOT EXISTS `horarios`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `rol` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `horarios`.`trabajador` (
  `idtrabajador` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(35) NOT NULL,
  `celular` VARCHAR(13) NULL,
  `correo` VARCHAR(45) NULL,
  `fechaelim` TIMESTAMP(6) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idtrabajador`, `usuario_idusuario`),
  INDEX `fk_trabajador_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_trabajador_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `horarios`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`grupo` ;

CREATE TABLE IF NOT EXISTS `horarios`.`grupo` (
  `idgrupo` INT NOT NULL,
  `nombre` VARCHAR(4) NOT NULL,
  `salon` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`alumno` ;

CREATE TABLE IF NOT EXISTS `horarios`.`alumno` (
  `idalumno` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(35) NOT NULL,
  `idgrupo` INT NOT NULL,
  `fechaelim` TIMESTAMP(6) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idalumno`, `idgrupo`, `usuario_idusuario`),
  INDEX `fk_alumno_grupo_idx` (`idgrupo` ASC),
  INDEX `fk_alumno_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_alumno_grupo`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `horarios`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `horarios`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`periodo` ;

CREATE TABLE IF NOT EXISTS `horarios`.`periodo` (
  `idperiodo` INT NOT NULL,
  `tipo` VARCHAR(1) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`materia` ;

CREATE TABLE IF NOT EXISTS `horarios`.`materia` (
  `idmateria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`clase` ;

CREATE TABLE IF NOT EXISTS `horarios`.`clase` (
  `idclase` INT NOT NULL,
  `idalumno` INT NOT NULL,
  `idgrupo` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `periodo_idperiodo` INT NOT NULL,
  `hora` VARCHAR(9) NOT NULL,
  `dia` VARCHAR(9) NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`idclase`, `periodo_idperiodo`),
  INDEX `fk_alumno_has_trabajador_trabajador1_idx` (`idtrabajador` ASC),
  INDEX `fk_alumno_has_trabajador_alumno1_idx` (`idalumno` ASC, `idgrupo` ASC),
  INDEX `fk_clase_periodo1_idx` (`periodo_idperiodo` ASC),
  INDEX `fk_clase_materia1_idx` (`materia_idmateria` ASC),
  CONSTRAINT `fk_alumno_has_trabajador_alumno1`
    FOREIGN KEY (`idalumno` , `idgrupo`)
    REFERENCES `horarios`.`alumno` (`idalumno` , `idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_trabajador_trabajador1`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `horarios`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `horarios`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `horarios`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`asisAlumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`asisAlumno` ;

CREATE TABLE IF NOT EXISTS `horarios`.`asisAlumno` (
  `idasisAlumno` INT NOT NULL,
  `idclase` INT NOT NULL,
  `idperiodo` INT NOT NULL,
  `hora` VARCHAR(9) NOT NULL,
  `dia` VARCHAR(9) NOT NULL,
  `registro` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idasisAlumno`, `idclase`, `idperiodo`),
  INDEX `fk_asisAlumno_clase1_idx` (`idclase` ASC, `idperiodo` ASC),
  CONSTRAINT `fk_asisAlumno_clase1`
    FOREIGN KEY (`idclase` , `idperiodo`)
    REFERENCES `horarios`.`clase` (`idclase` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`asisTrabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`asisTrabajador` ;

CREATE TABLE IF NOT EXISTS `horarios`.`asisTrabajador` (
  `idasisTrabajador` INT NOT NULL,
  `idclase` INT NOT NULL,
  `idperiodo` INT NOT NULL,
  `hora` VARCHAR(9) NOT NULL,
  `dia` VARCHAR(9) NOT NULL,
  `registro` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idasisTrabajador`, `idclase`, `idperiodo`),
  INDEX `fk_asisTrabajador_clase1_idx` (`idclase` ASC, `idperiodo` ASC),
  CONSTRAINT `fk_asisTrabajador_clase1`
    FOREIGN KEY (`idclase` , `idperiodo`)
    REFERENCES `horarios`.`clase` (`idclase` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
